version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark_master:
    image: 47deg/spark:1.6.3
    ports:
    - "7077:7077"
    - "8080:8080"
    container_name: spark_master
    tty: true
    command: /start-master.sh

  spark_worker:
    image: 47deg/spark:1.6.3
    links:
      - spark_master
    command: /start-worker.sh 
